/* Leetcode Problem 389 Find the difference
 You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/
import java.util.Arrays;
class Day_76 {
    public char findTheDifference(String s, String t) {
char[] schar=s.toCharArray();
      char[] tchar=t.toCharArray(); 
        
        Arrays.sort(schar);
        Arrays.sort(tchar);
        
        for(int i=0; i<schar.length; i++){
            if(schar[i]!=tchar[i]){return tchar[i];}
        }
        return tchar[tchar.length-1];
    }}
    //Sample Test Cases
/*
     Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 
     */
